spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.1.11.110:3310/baojia_bike?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: baojia_xm
#    password: DgisNKhg
#  cache:
#    jcache:
#      config: classpath:ehcache:xml

  kafka:
    bootstrap-servers: 121.40.109.63:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: hello

management:
  endpoints:
    web:
      exposure:
        include: health,debug,loggers
#mybatis的相关配置
#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.erlong.mybatis.entity
#  #开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    cacheEnabled: false




